### ISSUE TITLE
Result Layer Symbology

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#538]
Symbology will be managed in AGOL layer with nice looking defaults if there is no custom symbol.

If we can't find a great way to figure out if there is a custom symbol defined in AGOL, we could use a boolean field in the config spreadsheet.

**Comment by nathankota** [comment]
looks like **Public Water System Facilities** in the app matches the symbology of [Utah DDW Public Water System Sources](https://utahdeq.maps.arcgis.com/home/item.html?id=6f9b547041544320b8788e3e45b9d914). 

What are some other AGOL layers with custom symbology to test? Otherwise the defaults look quite good.

**Comment by nathankota** [comment]
> What are some other AGOL layers with custom symbology to test? Otherwise the defaults look quite good.

All the Environmental Justice (EJ) layer

**Comment by nathankota** [comment]
Custom polygon symbology is hard to decipher with multiple polygon layer searches, but that is expected with overlaid polygons; however, I am seeing the preservation of AGOL custom layer symbology with individual poly searches, so I'm validating.
