### ISSUE TITLE
Support field aliases for result grid

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#543]
Request from Deidre. This should be done in a similar manner to the field aliases for the feature identify table. 

Maybe these could be done natively via AGOL rather than in the config spreadsheet?

**Comment by nathankota** [comment]
> Maybe these could be done natively via AGOL rather than in the config spreadsheet?
@stdavis did you end up implementing the AGOL aliases, rather than config? I see that the result grid fields match the AGOL (open data) fields, and I deployed a change to the config (SITENAME to SITE_NAME) which did not show in the app, so I'm guessing you matched it to the AGOL alias, but I want to make sure I'm testing the right thing.

**Comment by stdavis** [comment]
Yes, your assumption is correct. I implemented the AGOL aliases. Sorry, I should have updated this issue with this clarification. I may need to delete more unused columns in the config spreadsheet to eliminate confusion.

**Comment by nathankota** [comment]
I tested seven or so layers and the app aliases all matched the AGOL aliases.
